apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "rqcluster.example.com/v1alpha1",
          "kind": "Rqcluster",
          "metadata": {
            "name": "example-rqcluster"
          },
          "spec": {
            "size": 3
          },
          "status": {
            "nodes": null
          }
        }
      ]
    capabilities: Basic Install
  name: rq.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Placeholder description
  displayName: Rq
  install:
    spec:
      deployments:
      - name: rq
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: rq
          strategy: {}
          template:
            metadata:
              labels:
                name: rq
            spec:
              containers:
              - command:
                - rq
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: rq
                image: quay.io/jemccorm/rq-operator:v0.0.1
                imagePullPolicy: Always
                name: rq
                resources: {}
              serviceAccountName: rq
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - rq
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - rqcluster.example.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: rq
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: rq.v0.0.0
  version: 0.0.1
