apiVersion: rqcluster.example.com/v1alpha1
kind: Rqcluster
metadata:
  name: example-rqcluster
status:
  nodes: 
spec:
  # Add fields here
  size: 3
  memory: '100m'
  storage: 'standard'
  cpu: '100'
