apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rq
  name: rqpod1
  namespace: default
spec:
  containers:
  - name: rqlite
    image: jmccormick2001/rqlite:v0.0.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 4001
      name: rqport1
      protocol: TCP
    - containerPort: 4002
      name: rqport2
      protocol: TCP
    volumeMounts:
    - mountPath: /rqlite/file
      name: rqlite-storage
      readOnly: false
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - name: rqlite-storage
    emptyDir: {}
