apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rqleader
  name: rqpod1
  namespace: rqnamespace
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: leader
              operator: In
              values:
              - "true"
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: rqlite
    image: quay.io/jemccorm/rqlite:v0.0.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 160Mi
    ports:
    - containerPort: 4001
      name: rqhttps
      protocol: TCP
    volumeMounts:
    - mountPath: /rqlite/file
      name: rqlite-storage
      readOnly: false
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - name: rqlite-storage
    emptyDir: {}
