apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rqlite
  name: rqpod2
  namespace: default
spec:
  containers:
  - name: rqlite
    image: jmccormick2001/rqlite:v0.0.1
    imagePullPolicy: IfNotPresent
    env:
    - name: JOIN_ADDRESS
      value: "-join http://rqleader:4001"
    ports:
    - containerPort: 4001
      name: rqhttps
      protocol: TCP
    volumeMounts:
    - mountPath: /rqlite/file
      name: rqlite-storage
      readOnly: false
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - name: rqlite-storage
    emptyDir: {}
